config/routes.rb
Rails.application.routes.draw do
  root "contacts#index"

  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :group, optional: true

  validates :name, presence: { message: "名字不能为空" }

  scope :search, -> (term) do
      where('LOWER(name) LIKE :term', term: "%#{term.downcase}%") if term.present?
  end 

  scope :by_group, -> (group_id) { where(group_id: group_id) if group_id.present? }
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale 

  private
    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale 
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact, only: [:show, :edit, :update, :destroy]
  
  def index
    session[:selected_group_id] = params[:group_id]
    @contacts = Contact.by_group(params[:group_id]).search(params[:term]).order("created_at desc").page(params[:page])
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:success] = "新建成功"
      redirect_to contacts_path(previous_query_string)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      flash[:success] = "更新成功"
      redirect_to contacts_path(previous_query_string)
    else
      render 'edit'
    end
  end

  def destroy
    @contact.destroy
    flash[:success] = "删除成功"
    redirect_to contacts_path(previous_query_string)
  end

  private
    def find_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:name, :company, :email, :phone, :address, :group_id)
    end

    def previous_query_string
      session[:selected_group_id] ? { group_id: session[:selected_group_id] } : {}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<tr>
  <td class="text-left"><%= contact.name %></td>
  <td class="text-right">
    <%= link_to "编辑", edit_contact_path(contact), class: "badge badge-primary" %>
    <%= link_to "删除", contact, method: :delete, data: { confirm: "确定删除?"}, class: "badge badge-danger" %>
  </td>
</tr>

app/views/contacts/_form.html.erb
    <div class="card">
      <div class="card-header text-secondary text-center">
        <%= @contact.new_record? ? "新建信息" : "编辑信息" %>
      </div>
      <div class="card-body">
        <%= render partial: 'shared/errors', locals: { demo: @contact } %>
        <%= form_for(@contact,
                     url: (@contact.new_record? ? contacts_path : contact_path(@contact)),
                     method: (@contact.new_record? ? 'post' : 'put')) do |f| %>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">名称:</label>
          <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control", autofocus: true %>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">公司:</label>
          <div class="col-sm-10">
            <%= f.text_field :company, class: "form-control", autofocus: true %>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">邮箱:</label>
          <div class="col-sm-10">
            <%= f.text_field :email, class: "form-control", autofocus: true %>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">手机:</label>
          <div class="col-sm-10">
            <%= f.text_field :phone, class: "form-control", autofocus: true %>
          </div>
        </div> 

        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">地址:</label>
          <div class="col-sm-10">
            <%= f.text_field :address, class: "form-control", autofocus: true %>
          </div>
        </div>
        
        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">分类:</label>
          <div class="col-sm-10">
            <% attr = { prompt: "Select Group" } %>
            <% attr[:selected] = session[:selected_group_id].to_i if session[:selected_group_id] %>
            <%= f.collection_select :group_id, Group.all, :id, :name, attr, {class: "form-control" } %>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label"></label>
          <div class="col-sm-10">
            <%= f.submit (@contact.new_record? ? "创建信息" : "更新信息"), class: "btn btn-primary btn-sm"%>
          </div>
        </div>
        
        <% end %>
      </div>
    </div>

app/views/contacts/edit.html.erb
<div class="row">
  <%= render 'shared/left_bar' %>
  <div class="col-md-9">
    <%= render 'form' %>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="row">
  <%= render 'shared/left_bar' %>
  <div class="col-md-9">
    <% if @contacts.blank? %>
      <div class="alert alert-primary" role="alert">
       no records
      </div> 
    <% end %>
    <table class="table">
      <%= render @contacts %>
    </table>
    <%= paginate @contacts %>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="row">
  <%= render 'shared/left_bar' %>
  <div class="col-md-9">
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>用户管理系统</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% unless demo.errors.blank? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <% demo.errors.messages.values.flatten.each do |error| %>
        <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
      <% end -%>
    </ul>
  </div>
<% end -%>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_left_bar.html.erb
<div class="col-md-3">
  <ul class="list-group">
    <% active = (params[:group_id] == nil || params[:group_id].empty?) && !session[:selected_group_id] ? 'active' : '' %>
    <%= link_to contacts_path, class: "list-group-item d-flex justify-content-between align-items-center #{active}" do %>
      all contact
      <span class="badge badge-primary badge-pill"><%= Contact.count %></span>
    <% end %>
    <% Group.all.each do |group| %>
      <% active = params[:group_id].to_i == group.id || (session[:selected_group_id] && session[:selected_group_id].to_i == group.id) ? 'active' : '' %>
      <%= link_to contacts_path(group_id: group.id), class: "list-group-item d-flex justify-content-between align-items-center #{active}" do %>
        <%= group.name %>
        <span class="badge badge-primary badge-pill"><%= group.contacts.count %></span>
      <% end %>
    <% end %>
  </ul> 
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light mb-3">
        <div class="container">
          <a class="navbar-brand" href="<%= root_path %>">信息管理系统</a>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to new_contact_path, class: "nav-link btn btn-sm btn-outline-light" do %>
                    <i class="fa fa-plus"></i>
                    新建信息
                  <% end %>
                </li>
                <li class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Dropdown</a>
                  <div class="dropdown-menu">
                    <a href="#" class="dropdown-item">Link 1</a>
                    <a href="#" class="dropdown-item">Link 2</a>
                    <a href="#" class="dropdown-item">Link 3</a>
                  </div>
                </li>
                <li class="nav-item">
                  <%= form_tag(contacts_path, class: "form-inline my-2 my-lg-0", method: :get) do %>
                    <%= hidden_field_tag :group_id, params[:group_id] %>
                    <%= text_field_tag :term, params[:term], class: "form-control mr-sm-1", placeholder: "Search..." %>
                    <button class="btn btn-link input-group-addon" type="submit"><i class="fa fa-search input-group-addon"></i></button>
                  <% end -%>
                </li>
              </ul>

          </div>
    </nav>